import { Inter } from "next/font/google";
import "./globals.css";
import BasketProvider from "./context/BasketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Unique Burger🍔",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BasketProvider>{children}</BasketProvider>
      </body>
    </html>
  );
}
